require 'rest_client'
require 'thor'
require 'json'
require 'fileutils'
require 'rest_client'
require 'yaml'

require_relative 'sbire/sbire_config'
require_relative 'sbire/command'
require_relative 'sbire/notifier'
require_relative 'sbire/audio_converter'
require_relative 'sbire/command_manager'
require_relative 'sbire/audio_recorder'
require_relative 'sbire/save_manager'
require_relative 'sbire/pipe_manager'
require_relative 'sbire/stream_manager'
require_relative 'sbire/pid_manager'
require_relative 'sbire/os'
